-- Remove vulnerable storage policies that allow token holders to access any client's documents
-- These policies checked if ANY valid token exists, not if the USER'S token matches the client folder

-- Drop the overly permissive policy that allows any access to client-documents bucket
DROP POLICY IF EXISTS "Token holders can view their documents in storage" ON storage.objects;

-- Drop the policy that checks for ANY valid token, not the user's specific token
DROP POLICY IF EXISTS "Token holders can view their client folder" ON storage.objects;

-- NOTE: Token-based document access will now use signed URLs generated by the 
-- get-signed-document-url Edge Function, which properly validates that the
-- token belongs to the specific client whose documents are being accessed.
-- This prevents cross-client document access attacks.